# Generated by Django 3.2.16 on 2022-12-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_alter_action_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
